set -s escape-time 0
set -g default-terminal "screen-256color"
set-window-option -g mode-keys vi
set -g focus-events on

# change default prefix to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split vertically
bind ) split-window -h

# split horizontally
bind = split-window -v -l 20%

# switch focus to other panes
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# resize panes
bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

#unbind arrow keys
unbind Left
unbind Down
unbind Up
unbind Right

